branches:
  only:
  - master
language: csharp
install:
  - nuget pack Microsoft.Azure.IoT.Edge.Function.nuspec -NoDefaultExcludes
  - FILENAME="$(find . -name '*.nupkg')"
  - nuget push "${FILENAME}" $APIKEY -Source $PACKAGE_SOURCE
script:
  - echo "success"
